--CREATE TRIGGER role_tg_audit AFTER INSERT OR UPDATE OR DELETE ON role FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   methodology_audit AFTER INSERT OR UPDATE OR DELETE ON methodology FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   metric_audit AFTER INSERT OR UPDATE OR DELETE ON metric FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   feature_audit AFTER INSERT OR UPDATE OR DELETE ON feature FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   role_audit AFTER INSERT OR UPDATE OR DELETE ON role FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   person_audit AFTER INSERT OR UPDATE OR DELETE ON person FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   responsevalue_audit AFTER INSERT OR UPDATE OR DELETE ON responsevalue FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   project_audit AFTER INSERT OR UPDATE OR DELETE ON project FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   teamproject_audit AFTER INSERT OR UPDATE OR DELETE ON teamproject FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   subdimension_audit AFTER INSERT OR UPDATE OR DELETE ON subdimension FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   participation_audit AFTER INSERT OR UPDATE OR DELETE ON participation FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   rolesubdimension_audit AFTER INSERT OR UPDATE OR DELETE ON rolesubdimension FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   typefacility_audit AFTER INSERT OR UPDATE OR DELETE ON typefacility FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   typequestion_audit AFTER INSERT OR UPDATE OR DELETE ON typequestion FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   user_audit AFTER INSERT OR UPDATE OR DELETE ON public.user FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   subfeature_audit AFTER INSERT OR UPDATE OR DELETE ON subfeature FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   variable_audit AFTER INSERT OR UPDATE OR DELETE ON variable FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   attribute_audit AFTER INSERT OR UPDATE OR DELETE ON attribute FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   facility_audit AFTER INSERT OR UPDATE OR DELETE ON facility FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   version_audit AFTER INSERT OR UPDATE OR DELETE ON version FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   optionquestion_audit AFTER INSERT OR UPDATE OR DELETE ON optionquestion FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();

CREATE TRIGGER   PHCPhase_audit AFTER INSERT OR UPDATE OR DELETE ON public.PHCPhase FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();

CREATE TRIGGER   method_audit AFTER INSERT OR UPDATE OR DELETE ON method FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   dimension_audit AFTER INSERT OR UPDATE OR DELETE ON dimension FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   userrole_audit AFTER INSERT OR UPDATE OR DELETE ON userrole FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();
CREATE TRIGGER   question_audit AFTER INSERT OR UPDATE OR DELETE ON question FOR EACH ROW EXECUTE PROCEDURE fn_log_audit();


SELECT * FROM  public.tbl_audit;

--DROP TRIGGER IF EXISTS role_tg_audit ON role;

--select * from pg_trigger;

--select * from information_schema.tables where table_schema='public';